// ─── Types ───────────────────────────────────────────────────────────────────

export interface ProjectData {
  id: string
  index: number
  icon: string
  title: string
  subtitle: string
  description: string
  tech: string[]
  accent: string
  glowClass: 'glow-violet' | 'glow-blue' | 'glow-green'
  category: 'school' | 'personal'
  year: string
  liveUrl?: string
  codeUrl?: string
}

// ─── Helper de résolution d'URL ──────────────────────────────────────────────
const isProd = process.env.NODE_ENV === 'production';
export const basePath = isProd ? '/mon-portfolio-it' : '';

export function resolveProjectUrl(url?: string): string {
  if (!url) return '';
  if (url.startsWith('http://') || url.startsWith('https://') || url.startsWith('#') || url.startsWith('mailto:')) {
    return url;
  }
  const clean = url.startsWith('/') ? url : `/${url}`;
  return `${basePath}${clean}`;
}

// ─── Projets Scolaires (15 projets complets avec démos réelles) ───────────────

export const schoolProjects: ProjectData[] = [
  {
    id: 'tp1-boutique',
    index: 0,
    icon: '🛒',
    title: 'Boutique en ligne',
    subtitle: 'HTML/CSS/JS — Grille de produits & panier',
    description: 'Premier TP de mise en page complexe. Une boutique avec une grille de produits CSS et un panier latéral fonctionnel en JS. Code basique mais fonctionnel.',
    tech: ['HTML', 'CSS', 'JavaScript', 'CSS Grid'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP1.html',
  },
  {
    id: 'tp2-bts',
    index: 1,
    icon: '🖥️',
    title: 'Présentation BTS SIO',
    subtitle: 'Découverte du cursus — HTML structuré',
    description: 'Première page avec une vraie structure sémantique. Présentation du BTS SIO, options SLAM/SISR, débouchés. Début de la compréhension des balises HTML.',
    tech: ['HTML', 'CSS'],
    accent: '#3D9EFF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP2.html',
  },
  {
    id: 'tp3-metiers',
    index: 2,
    icon: '🗂️',
    title: 'Fiches Métiers IT',
    subtitle: 'Navigation multi-pages — HTML/CSS/JS',
    description: 'Site de présentation de 5 métiers IT (Pentester, DevSecOps, Dev Web, Admin Réseau, Cloud) avec navigation sidebar. Premier vrai travail de structure multi-pages.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#34D058',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP3.html',
  },
  {
    id: 'tp5-form',
    index: 3,
    icon: '📬',
    title: 'Formulaire de contact',
    subtitle: 'HTML5 + CSS — Validation et mise en page',
    description: 'Formulaire de contact complet avec validation JS : nom, prénom, email, téléphone, sujet et message. Première maîtrise des formulaires HTML avec feedback utilisateur.',
    tech: ['HTML5', 'CSS', 'JavaScript'],
    accent: '#FF375F',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP5.html',
  },
  {
    id: 'tp7-calc',
    index: 4,
    icon: '🧮',
    title: 'Calculatrice JavaScript',
    subtitle: 'DOM + fonctions JS — Calculatrice fonctionnelle',
    description: 'Calculatrice avec les 4 opérations arithmétiques, test de parité et permutation des valeurs. Premier vrai projet interactif JS avec manipulation du DOM.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#64D2FF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP7.html',
  },
  {
    id: 'tp8-ferrari',
    index: 5,
    icon: '🏎️',
    title: 'Site Ferrari',
    subtitle: 'Bootstrap 5 — Mise en page responsive',
    description: 'Site de présentation Ferrari avec navbar Bootstrap, grille responsive, galerie et section statistiques. Découverte et prise en main des frameworks CSS modernes.',
    tech: ['HTML', 'Bootstrap 5'],
    accent: '#FF375F',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP8.html',
  },
  {
    id: 'tp9-fonctions',
    index: 6,
    icon: '⚙️',
    title: 'Fonctions JS interactives',
    subtitle: 'Calcul moyenne, test âge, changement de fond',
    description: 'Exercices JS variés : calcul de moyenne avec invites prompt, test de majorité, affichage nom/prénom, modification dynamique de la couleur de fond.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#30D158',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP9.html',
  },
  {
    id: 'tp10-avance',
    index: 7,
    icon: '🔬',
    title: 'Logique JS avancée',
    subtitle: 'Conditions imbriquées, comparaisons, Math.random()',
    description: 'Évolution avec des cas plus complexes : mentions scolaires, analyse de température, comparaison de deux nombres, générateur de nombres aléatoires.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP10.html',
  },
  {
    id: 'tp11-calc-avance',
    index: 8,
    icon: '🧪',
    title: 'Calculatrice multi-fonctions',
    subtitle: 'Puissance, racine, PGCD — JS scientifique',
    description: 'Calculatrice scientifique avec opérations avancées : puissances, racines carrées, parité et calcul de PGCD. Code plus modulaire et rigoureux.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#FF6B85',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/TP11.html',
  },
  {
    id: 'tp12-data',
    index: 9,
    icon: '📊',
    title: 'Analyseur de données',
    subtitle: 'Tableaux JS — tri, moyenne, parité',
    description: 'Analyse dynamique d\'une série de nombres : calcul de moyenne, min/max, tri croissant/décroissant et répartition pair/impair. Manipulation d\'arrays en JS.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Array'],
    accent: '#FFB340',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/TP12.html',
  },
  {
    id: 'tp-bootstrap',
    index: 10,
    icon: '🧱',
    title: 'Dashboard Lab IT',
    subtitle: 'Bootstrap 5 — Interface admin responsive',
    description: 'Interface d\'administration de laboratoire IT avec sidebar, inventaire des serveurs en ligne, postes clients et statistiques réseau en temps réel.',
    tech: ['HTML', 'CSS', 'Bootstrap 5'],
    accent: '#64D2FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/TP_Bootstrap.html',
  },
  {
    id: 'jmerise',
    index: 11,
    icon: '🗃️',
    title: 'MCD — Gestion Militaire',
    subtitle: 'Merise — Modélisation base de données',
    description: 'Modélisation relationnelle d\'une base de données militaire : entités GRADE, MILITAIRE, UNITÉ, MISSION, BASE. Dictionnaire de données et script SQL généré.',
    tech: ['SQL', 'Merise', 'MCD', 'HTML'],
    accent: '#34D058',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/JMerise.html',
  },
  {
    id: 'php-reservations',
    index: 12,
    icon: '🚌',
    title: 'Gestion de réservations',
    subtitle: 'PHP & MySQL — CRUD voitures / chauffeurs',
    description: 'Application web pour gérer des réservations de cars touristiques : assignation véhicule/chauffeur, gestion des disponibilités, requêtes préparées PDO.',
    tech: ['PHP', 'MySQL', 'PDO', 'HTML', 'CSS'],
    accent: '#FF375F',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/php-reservations.html',
  },
  {
    id: 'centre-formation',
    index: 13,
    icon: '🎓',
    title: 'Plateforme de formation',
    subtitle: 'PHP/MySQL multi-rôles — Admin / Enseignant / Étudiant',
    description: 'Système de gestion académique avec authentification, contrôle d\'accès basé sur les rôles (RBAC), gestion des cours, étudiants et relevés de notes.',
    tech: ['PHP', 'MySQL', 'CSS', 'Sessions', 'RBAC'],
    accent: '#64D2FF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/centre-formation.html',
  },
  {
    id: 'windows-server-lab',
    index: 14,
    icon: '🖧',
    title: 'Lab Windows Server',
    subtitle: 'Active Directory, DNS, DHCP Failover — PowerShell',
    description: 'Déploiement automatisé d\'une infrastructure réseau d\'entreprise virtualisée sur 3 serveurs : routage NAT, Active Directory répliqué, DHCP en haute disponibilité.',
    tech: ['Windows Server', 'PowerShell', 'Active Directory', 'DNS', 'DHCP'],
    accent: '#30D158',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/windows-server-lab.html',
    codeUrl: 'https://github.com/danonmarvin8-gif/mon-portfolio-it',
  },
]

// ─── Projets Personnels (100% fonctionnels et accessibles) ───────────────────

export const personalProjects: ProjectData[] = [
  {
    id: 'upside-down',
    index: 0,
    icon: '🌀',
    title: 'The Upside Down',
    subtitle: 'Portfolio Stranger Things — Expérience interactive',
    description: 'Premier portfolio personnel complet : ambiance Stranger Things, effets sonores, portail animé CSS, missions d\'investigation et certifications.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Web Audio API'],
    accent: '#FF375F',
    glowClass: 'glow-violet',
    category: 'personal',
    year: '2024',
    liveUrl: '/projects/upside-down/index.html',
  },
  {
    id: 'disney-cast',
    index: 1,
    icon: '✨',
    title: 'Disney Cast Member',
    subtitle: 'Candidature interactive — Vidéo & Canvas',
    description: 'Portfolio de candidature pour Disneyland Paris : cinématique vidéo plein écran, système de particules dorées sur Canvas et interface glassmorphism.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Canvas API', 'Video API'],
    accent: '#FFD60A',
    glowClass: 'glow-blue',
    category: 'personal',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/Portfolio-Disney-Cast-Member-Danon-Marvin/',
    codeUrl: 'https://github.com/danonmarvin8-gif/Portfolio-Disney-Cast-Member-Danon-Marvin',
  },
  {
    id: 'dbz-portfolio',
    index: 2,
    icon: '🐉',
    title: 'DBZ Portfolio',
    subtitle: 'Dragon Ball Z — Scouter HUD, aura Canvas',
    description: 'Portfolio thème Dragon Ball Z avec affichage tête haute (HUD Scouter), aura de combat générée par Canvas et mini-arcade interactive.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Canvas API'],
    accent: '#FF9F0A',
    glowClass: 'glow-green',
    category: 'personal',
    year: '2025',
    liveUrl: '/projects/dbz/index.html',
  },
  {
    id: 'omega-os',
    index: 3,
    icon: '🤖',
    title: 'OMEGA OS',
    subtitle: 'Spatial Launcher — MediaPipe & Three.js',
    description: 'Système d\'exploitation spatial contrôlable par les gestes de la main via webcam. Computer vision MediaPipe, scène 3D temps réel Three.js et Electron.',
    tech: ['Electron', 'Three.js', 'MediaPipe', 'JavaScript'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'personal',
    year: '2025',
    liveUrl: '/projects/omega-os.html',
    codeUrl: 'https://github.com/danonmarvin8-gif/mon-portfolio-it',
  },
]
