// ─── Types ───────────────────────────────────────────────────────────────────

export interface ProjectData {
  id: string
  index: number
  icon: string
  title: string
  subtitle: string
  description: string
  tech: string[]
  accent: string
  glowClass: 'glow-violet' | 'glow-blue' | 'glow-green'
  category: 'school' | 'personal'
  year: string
  liveUrl?: string
  codeUrl?: string
}

// ─── Projets Scolaires ───────────────────────────────────────────────────────
// Les TPs sont hébergés dans /public/tps/ — thème neutre pro, zéro Stranger Things.

export const schoolProjects: ProjectData[] = [
  {
    id: 'tp1-boutique',
    index: 0,
    icon: '🛒',
    title: 'Boutique en ligne',
    subtitle: 'HTML/CSS/JS — Grille de produits & panier',
    description: 'Premier TP de mise en page complexe. Une boutique avec une grille de produits CSS et un panier latéral fonctionnel en JS. Code basique mais ça marche.',
    tech: ['HTML', 'CSS', 'JavaScript', 'CSS Grid'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP1.html',
  },
  {
    id: 'tp2-bts',
    index: 1,
    icon: '🖥️',
    title: 'Présentation BTS SIO',
    subtitle: 'Découverte du cursus — HTML structuré',
    description: 'Première page avec une vraie structure sémantique. Présentation du BTS SIO, options SLAM/SISR, débouchés. Début de la compréhension des balises HTML.',
    tech: ['HTML', 'CSS'],
    accent: '#3D9EFF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP2.html',
  },
  {
    id: 'tp3-metiers',
    index: 2,
    icon: '🗂️',
    title: 'Fiches Métiers IT',
    subtitle: 'Navigation multi-pages — HTML/CSS/JS',
    description: 'Site de présentation de 5 métiers IT (Pentester, DevSecOps, Dev Web, Admin Réseau, Cloud) avec navigation sidebar. Premier vrai travail de structure multi-pages.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#34D058',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP3.html',
  },
  {
    id: 'tp5-form',
    index: 3,
    icon: '📬',
    title: 'Formulaire de contact',
    subtitle: 'HTML5 + CSS — Validation et mise en page',
    description: 'Formulaire de contact complet avec validation JS : nom, prénom, email, téléphone, sujet et message. Première maîtrise des formulaires HTML avec feedback utilisateur.',
    tech: ['HTML5', 'CSS', 'JavaScript'],
    accent: '#FF375F',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP5.html',
  },
  {
    id: 'tp7-calc',
    index: 4,
    icon: '🧮',
    title: 'Calculatrice JavaScript',
    subtitle: 'DOM + fonctions JS — Calculatrice fonctionnelle',
    description: 'Calculatrice avec les 4 opérations, test de parité et permutation des valeurs. Premier vrai projet interactif JS — la logique de manipulation du DOM commence à faire sens.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#64D2FF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP7.html',
  },
  {
    id: 'tp8-ferrari',
    index: 5,
    icon: '🏎️',
    title: 'Site Ferrari',
    subtitle: 'Bootstrap 5 — Mise en page responsive',
    description: 'Site de présentation Ferrari avec navbar Bootstrap, grille responsive, galerie et section stats. Premier vrai usage d\'un framework CSS — ça m\'a montré la puissance des grilles.',
    tech: ['HTML', 'Bootstrap 5'],
    accent: '#FF375F',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP8.html',
  },
  {
    id: 'tp9-fonctions',
    index: 6,
    icon: '⚙️',
    title: 'Fonctions JS interactives',
    subtitle: 'Calcul moyenne, test âge, changement de fond',
    description: 'Exercices JS variés : calcul de moyenne avec prompt, test majorité, affichage nom/prénom, changement de couleur de fond. Beaucoup de `document.write` et `prompt` — c\'est de l\'époque.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#30D158',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP9.html',
  },
  {
    id: 'tp10-avance',
    index: 7,
    icon: '🔬',
    title: 'Logique JS avancée',
    subtitle: 'Conditions imbriquées, comparaisons, Math.random()',
    description: 'Évolution du TP9 avec des cas plus complexes : mention scolaire, analyse de température, comparaison de deux nombres, générateur aléatoire. Les conditions s\'emboîtent mieux.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: '/tps/TP10.html',
  },
  {
    id: 'tp11-calc-avance',
    index: 8,
    icon: '🧪',
    title: 'Calculatrice multi-fonctions',
    subtitle: 'Puissance, racine, PGCD — JS scientifique',
    description: 'Calculatrice plus poussée avec opérations scientifiques : puissance, racine carrée, parité et PGCD. Code plus structuré qu\'au TP7 — on voit la progression.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#FF6B85',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/TP11.html',
  },
  {
    id: 'tp12-data',
    index: 9,
    icon: '📊',
    title: 'Analyseur de données',
    subtitle: 'Tableaux JS — tri, moyenne, parité',
    description: 'Analyse dynamique d\'une liste de nombres : calcul de moyenne, min/max, tri croissant/décroissant et répartition pair/impair. Première vraie utilisation des tableaux JS.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Array'],
    accent: '#FFB340',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/TP12.html',
  },
  {
    id: 'tp-bootstrap',
    index: 10,
    icon: '🧱',
    title: 'Dashboard Lab IT',
    subtitle: 'Bootstrap 5 — Interface admin responsive',
    description: 'Interface d\'administration de laboratoire IT avec sidebar, tableau de serveurs, inventaire postes et stats réseau. Bootstrap mieux maîtrisé que le TP8 Ferrari.',
    tech: ['HTML', 'CSS', 'Bootstrap 5'],
    accent: '#64D2FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/TP_Bootstrap.html',
  },
  {
    id: 'jmerise',
    index: 11,
    icon: '🗃️',
    title: 'MCD — Gestion Militaire',
    subtitle: 'Merise — Modélisation base de données',
    description: 'Modélisation d\'une base de données de gestion de grades militaires : entités GRADE, MILITAIRE, UNITÉ, MISSION, BASE. Dictionnaire de données et SQL généré.',
    tech: ['SQL', 'Merise', 'MCD', 'HTML'],
    accent: '#34D058',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: '/tps/JMerise.html',
  },
  {
    id: 'php-reservations',
    index: 12,
    icon: '🚌',
    title: 'Gestion de réservations',
    subtitle: 'PHP & MySQL — CRUD voitures / chauffeurs',
    description: 'Application web pour gérer des réservations de cars touristiques. Menu de navigation, affichage depuis une base SQL, requêtes PHP. Premier vrai projet backend fonctionnel.',
    tech: ['PHP', 'MySQL', 'HTML', 'CSS'],
    accent: '#FF375F',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
  },
  {
    id: 'centre-formation',
    index: 13,
    icon: '🎓',
    title: 'Plateforme de formation',
    subtitle: 'PHP/MySQL multi-rôles — Admin / Enseignant / Étudiant',
    description: 'Système de gestion avec authentification et trois niveaux d\'accès. Gestion des modules, étudiants, enseignants. Architecture MVC partielle. Le projet le plus ambitieux du BTS.',
    tech: ['PHP', 'MySQL', 'CSS', 'Sessions', 'RBAC'],
    accent: '#64D2FF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2025',
  },
  {
    id: 'windows-server-lab',
    index: 14,
    icon: '🖧',
    title: 'Lab Windows Server',
    subtitle: 'Active Directory, DNS, DHCP Failover — PowerShell',
    description: 'Déploiement automatisé d\'une infra réseau complète sur 3 serveurs Windows. Scripts PowerShell pour NAT, Active Directory, DHCP avec basculement et GPO de groupe.',
    tech: ['Windows Server', 'PowerShell', 'Active Directory', 'DNS', 'DHCP'],
    accent: '#30D158',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    codeUrl: 'https://github.com/danonmarvin8-gif/mon-portfolio-it',
  },
]

// ─── Projets Personnels ───────────────────────────────────────────────────────

export const personalProjects: ProjectData[] = [
  {
    id: 'upside-down',
    index: 0,
    icon: '🌀',
    title: 'The Upside Down',
    subtitle: 'Portfolio Stranger Things — HTML/CSS/JS vanilla',
    description: 'Mon premier vrai portfolio perso. Ambiance Stranger Things complète avec effets sonores, portal animé CSS et galerie de projets. Zéro framework — code JS maison.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Web Audio API'],
    accent: '#FF375F',
    glowClass: 'glow-violet',
    category: 'personal',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/',
  },
  {
    id: 'disney-cast',
    index: 1,
    icon: '✨',
    title: 'Disney Cast Member',
    subtitle: 'Portfolio candidature — Canvas, particules, vidéo',
    description: 'Portfolio de candidature pour Disney avec intro vidéo plein écran, particules magiques Canvas et glassmorphism. Le projet où j\'ai vraiment progressé sur Canvas API.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Canvas API', 'Video API'],
    accent: '#FFD60A',
    glowClass: 'glow-blue',
    category: 'personal',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/Portfolio%20Disney%20Cast%20Member%20Danon%20Marvin/',
  },
  {
    id: 'dbz-portfolio',
    index: 2,
    icon: '🐉',
    title: 'DBZ Portfolio',
    subtitle: 'Dragon Ball Z — Scouter HUD, aura Canvas',
    description: 'Portfolio thème Dragon Ball Z avec scouter HUD dynamique, aura Canvas animée et fond vidéo combat. Chaque section a son propre "power level".',
    tech: ['HTML', 'CSS', 'JavaScript', 'Canvas API'],
    accent: '#FF9F0A',
    glowClass: 'glow-green',
    category: 'personal',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/Portfolio%20dbz/',
  },
  {
    id: 'omega-os',
    index: 3,
    icon: '🤖',
    title: 'OMEGA OS',
    subtitle: 'Spatial Launcher — Electron, Three.js, MediaPipe',
    description: 'Simulation d\'un OS spatial contrôlable à la main via la webcam. Hand tracking MediaPipe, rendu 3D Three.js, app desktop Electron. Le projet le plus technique que j\'aie fait.',
    tech: ['Electron', 'Three.js', 'MediaPipe', 'JavaScript'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'personal',
    year: '2025',
    codeUrl: 'https://github.com/danonmarvin8-gif/mon-portfolio-it',
  },
]
