// ─── Types ───────────────────────────────────────────────────────────────────

export interface ProjectData {
  id: string
  index: number
  icon: string
  title: string
  subtitle: string
  description: string
  tech: string[]
  accent: string
  glowClass: 'glow-violet' | 'glow-blue' | 'glow-green'
  category: 'school' | 'personal'
  year: string
  liveUrl?: string   // lien demo / live
  codeUrl?: string   // lien github source
}

// ─── Projets Scolaires ───────────────────────────────────────────────────────

export const schoolProjects: ProjectData[] = [
  {
    id: 'tpgs1',
    index: 0,
    icon: '📄',
    title: 'Première Page Web',
    subtitle: 'HTML & Bootstrap — Initiation',
    description: 'Mon tout premier TP web. Une page simple avec des titres, un menu et un formulaire. Le code est basique, quelques balises mal fermées, mais c\'est là que tout a commencé.',
    tech: ['HTML', 'Bootstrap'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TPGS1/',
  },
  {
    id: 'tp2-bts',
    index: 1,
    icon: '🖥️',
    title: 'Présentation BTS SIO',
    subtitle: 'Découverte du cursus — HTML structuré',
    description: 'Présentation complète du BTS SIO : options SLAM et SISR, débouchés, compétences visées. Première page avec une vraie structure sémantique.',
    tech: ['HTML', 'CSS'],
    accent: '#3D9EFF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP2.html',
  },
  {
    id: 'tp3-iframes',
    index: 2,
    icon: '🗂️',
    title: 'Site Multi-Pages — Métiers IT',
    subtitle: 'Navigation par iframes — Structure HTML',
    description: 'Un site de présentation des métiers IT avec un sommaire latéral fixe et une zone de contenu en iframe. Pas le plus élégant, mais j\'ai compris la navigation multi-pages.',
    tech: ['HTML', 'CSS', 'Iframes'],
    accent: '#34D058',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP3_index.html',
  },
  {
    id: 'tp4-metiers',
    index: 3,
    icon: '👾',
    title: 'Fiches Métiers IT',
    subtitle: 'Pentester, DevSecOps, Admin Réseau, Cloud — HTML/CSS',
    description: 'Fiches descriptives pour 5 métiers IT (Pentester, DevSecOps, Dev Web, Admin Réseau, Cloud). Première vraie mise en page multi-pages avec navigation.',
    tech: ['HTML', 'CSS'],
    accent: '#FF9F0A',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP4_index.html',
  },
  {
    id: 'tp5-form',
    index: 4,
    icon: '📬',
    title: 'Formulaire de Contact',
    subtitle: 'Validation HTML & mise en page CSS',
    description: 'Formulaire de contact avec validation native HTML5 — Nom, Email, Téléphone, Message. Premier vrai travail de mise en page CSS propre.',
    tech: ['HTML', 'CSS'],
    accent: '#FF375F',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP5.html',
  },
  {
    id: 'tp7-calc',
    index: 5,
    icon: '🧮',
    title: 'Calculatrice JavaScript',
    subtitle: 'DOM + logique JS — Calculatrice fonctionnelle',
    description: 'Calculatrice complète en JavaScript vanilla : opérations de base, gestion des erreurs, interface boutons. Premier vrai projet interactif JS.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#64D2FF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP7.html',
  },
  {
    id: 'tp8-ferrari',
    index: 6,
    icon: '🏎️',
    title: 'Site Ferrari',
    subtitle: 'Bootstrap 5 — Mise en page responsive',
    description: 'Site de présentation Ferrari avec navbar Bootstrap, grille responsive, galerie images. Premier vrai usage d\'un framework CSS.',
    tech: ['HTML', 'Bootstrap 5'],
    accent: '#FF375F',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP8.html',
  },
  {
    id: 'tp9-fonctions',
    index: 7,
    icon: '⚙️',
    title: 'Fonctions JavaScript',
    subtitle: 'Fonctions, conditions, boucles',
    description: 'Exercices de programmation JS : fonctions pures, conditions imbriquées, boucles. C\'est ici que la logique algorithmique a vraiment commencé à s\'ancrer.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#30D158',
    glowClass: 'glow-green',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP9.html',
  },
  {
    id: 'tp10-avance',
    index: 8,
    icon: '🔬',
    title: 'JS Avancé',
    subtitle: 'Tableaux, objets, manipulation du DOM',
    description: 'Manipulation avancée : tableaux, objets JS, boucles complexes, modification du DOM en temps réel. Nette progression par rapport aux TP précédents.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP10.html',
  },
  {
    id: 'tp11-hawkins',
    index: 9,
    icon: '🧪',
    title: 'La Machine de Hawkins',
    subtitle: 'Outil de calcul expérimental — JS',
    description: 'Simulation d\'une station de calcul Stranger Things. Interface JS avec plusieurs fonctions de traitement de données. Premier mélange entre thème visuel et code fonctionnel.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#FF6B85',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP11.html',
  },
  {
    id: 'tp12-data',
    index: 10,
    icon: '📊',
    title: 'Analyseur de Données',
    subtitle: 'Traitement et affichage de données — JS',
    description: 'Station de contrôle pour analyser et afficher des données dynamiquement. Tri, filtrage, rendu conditionnel en JS pur.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    accent: '#FFB340',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP12.html',
  },
  {
    id: 'tp-bootstrap',
    index: 11,
    icon: '🧱',
    title: 'Interface Bootstrap',
    subtitle: 'Mise en page responsive — Bootstrap',
    description: 'Interface de laboratoire responsive avec Bootstrap : grille, composants, navbar. Maquette propre pour un lab IT fictif.',
    tech: ['HTML', 'CSS', 'Bootstrap'],
    accent: '#64D2FF',
    glowClass: 'glow-violet',
    category: 'school',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/TP_Bootstrap.html',
  },
  {
    id: 'jmerise',
    index: 12,
    icon: '🗃️',
    title: 'MCD — Gestion Militaire',
    subtitle: 'Merise / UML — Modélisation base de données',
    description: 'Modélisation conceptuelle d\'une base de données de gestion de grades militaires. Entités, associations, cardinalités. Introduction à la conception de BDD relationnelles.',
    tech: ['SQL', 'Merise', 'HTML'],
    accent: '#34D058',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/tps/jmerise_Exo1.html',
  },
  {
    id: 'php-reservations',
    index: 13,
    icon: '🚌',
    title: 'Gestion de Réservations',
    subtitle: 'PHP & MySQL — CRUD voitures / chauffeurs',
    description: 'Application web pour gérer des réservations de cars touristiques. Menu de navigation, affichage depuis une base SQL, requêtes PHP. Premier vrai projet backend fonctionnel.',
    tech: ['PHP', 'MySQL', 'HTML', 'CSS'],
    accent: '#FF375F',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
  },
  {
    id: 'centre-formation',
    index: 14,
    icon: '🎓',
    title: 'Plateforme Centre de Formation',
    subtitle: 'App multi-rôles PHP/MySQL — Admin / Enseignant / Étudiant',
    description: 'Système de gestion complet avec authentification, trois niveaux d\'accès distincts, gestion des modules, étudiants et enseignants. Architecture MVC partielle, CSS responsive.',
    tech: ['PHP', 'MySQL', 'CSS', 'Sessions', 'RBAC'],
    accent: '#64D2FF',
    glowClass: 'glow-blue',
    category: 'school',
    year: '2025',
  },
  {
    id: 'windows-server-lab',
    index: 15,
    icon: '🖧',
    title: 'Lab Windows Server',
    subtitle: 'Active Directory, DNS, DHCP Failover, GPO — PowerShell',
    description: 'Déploiement automatisé d\'une infrastructure réseau complète sur 3 serveurs Windows. Scripts PowerShell pour le routage NAT, Active Directory, DHCP avec basculement et GPO.',
    tech: ['Windows Server', 'PowerShell', 'Active Directory', 'DNS', 'DHCP'],
    accent: '#30D158',
    glowClass: 'glow-green',
    category: 'school',
    year: '2025',
    codeUrl: 'https://github.com/danonmarvin8-gif/mon-portfolio-it',
  },
]

// ─── Projets Personnels ───────────────────────────────────────────────────────

export const personalProjects: ProjectData[] = [
  {
    id: 'upside-down',
    index: 0,
    icon: '🌀',
    title: 'Portfolio "The Upside Down"',
    subtitle: 'Stranger Things — HTML/CSS/JS vanilla',
    description: 'Mon premier vrai portfolio perso. Ambiance Stranger Things, effets sonores, portal animé en CSS. Code JS maison sans framework.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Web Audio API'],
    accent: '#FF375F',
    glowClass: 'glow-violet',
    category: 'personal',
    year: '2024',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/',
  },
  {
    id: 'disney-cast',
    index: 1,
    icon: '✨',
    title: 'Portfolio Disney Cast Member',
    subtitle: 'Candidature interactive — Vidéo, Canvas, Particules',
    description: 'Portfolio de candidature pour Disney avec intro vidéo plein écran, particules magiques sur Canvas et glassmorphism.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Canvas API', 'Video API'],
    accent: '#FFD60A',
    glowClass: 'glow-blue',
    category: 'personal',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/Portfolio%20Disney%20Cast%20Member%20Danon%20Marvin/',
  },
  {
    id: 'dbz-portfolio',
    index: 2,
    icon: '🐉',
    title: 'DBZ Portfolio',
    subtitle: 'Super Sparking Zero — Canvas aura, Scouter HUD',
    description: 'Portfolio thème Dragon Ball Z avec scouter HUD dynamique, aura Canvas animée et fond vidéo combat. Chaque section a son propre "power level".',
    tech: ['HTML', 'CSS', 'JavaScript', 'Canvas API'],
    accent: '#FF9F0A',
    glowClass: 'glow-green',
    category: 'personal',
    year: '2025',
    liveUrl: 'https://danonmarvin8-gif.github.io/JobFlow-AI-Robot/Portfolio%20dbz/',
  },
  {
    id: 'omega-os',
    index: 3,
    icon: '🤖',
    title: 'OMEGA OS',
    subtitle: 'Spatial Launcher — Electron, Three.js, MediaPipe',
    description: 'Simulation d\'un OS spatial contrôlable à la main via la webcam. Hand tracking MediaPipe, rendu 3D Three.js, app desktop Electron.',
    tech: ['Electron', 'Three.js', 'MediaPipe', 'JavaScript'],
    accent: '#7B61FF',
    glowClass: 'glow-violet',
    category: 'personal',
    year: '2025',
    codeUrl: 'https://github.com/danonmarvin8-gif/mon-portfolio-it',
  },
]
